# .github/workflows/cd.yml
name: CD - Desplegar a Producción

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Desplegar en Render
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render Deployment
        uses: render-oss/render-deploy-action@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true # Esto hace que el workflow espere a que termine el despliegue
